# Change these first
owner: dapodix # Your GitHub username
repo: status # Your Github repository name


sites:
  - name: Dapo Kemdikbud
    url: https://dapo.kemdikbud.go.id/
  - name: Manajemen Dapodik
    url: http://datadik.kemdikbud.go.id/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: SP Datadik
    url: https://sp.datadik.kemdikbud.go.id/
  - name: PTK Datadik
    url: https://ptk.datadik.kemdikbud.go.id
  - name: Info GTK
    url: https://info.gtk.kemdikbud.go.id/
  - name: Portal BOS
    url: https://bos.kemdikbud.go.id/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: PMP Dikdasmen
    url: http://pmp.kemdikbud.go.id/
  - name: Pemetaan Mutu PAUD
    url: https://pemetaanmutu.paud-dikmas.kemdikbud.go.id/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Verval SP
    url: http://vervalsp.data.kemdikbud.go.id/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Verval PTK
    url: http://vervalptk.data.kemdikbud.go.id/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Verval PD
    url: http://vervalpd.data.kemdikbud.go.id/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Verval Ponsel
    url: https://vervalponsel.data.kemdikbud.go.id/
  - name: Verval Ijazah
    url: https://info.gtk.kemdikbud.go.id/verval_s1/index.php
  - name: Simdak PAUD
    url: https://app.paud-dikmas.kemdikbud.go.id/simdak/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: BANSM
    url: https://bansm.kemdikbud.go.id/
  - name: BAN PAUD & PNF
    url: https://banpaudpnf.kemdikbud.go.id/
  - name: BANPAUD&PNF Sispena
    url: https://banpaudpnf.kemdikbud.go.id/sispena/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: CDN Dapodik
    url: https://cdn-dapodik.kemdikbud.go.id/

status-website:
  name: Status Web Dapodik - Kemdikbud
  baseUrl: /status
  logoUrl: https://upload.wikimedia.org/wikipedia/commons/9/9c/Logo_of_Ministry_of_Education_and_Culture_of_Republic_of_Indonesia.svg
  introTitle: "**Dapodik** adalah acuan data yang digunakan oleh [Kemdikbud](https://www.kemdikbud.go.id/)."
  introMessage: Halaman ini berfungsi untuk memonitor website yang berhubungan dengan [Dapodik](https://dapo.kemdikbud.go.id/) dan [Kemdikbud](https://www.kemdikbud.go.id/)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Insiden Aktif
  allSystemsOperational: Semua sistem beroperasi
  incidentReport: "Laporan insiden #$NUMBER →"
  activeIncidentSummary: Dibuka pada $DATE dengan $POSTS postingan
  incidentTitle: Detail Insiden $NUMBER
  incidentDetails: Detail Insiden
  incidentFixed: Diperbaiki
  incidentOngoing: Sedang berlangsung
  incidentOpenedAt: Dibuka pada
  incidentClosedAt: Ditutup pada
  incidentSubscribe: Berlangganan Pembaruan
  incidentViewOnGitHub: Lihat di GitHub
  incidentCommentSummary: Diposting pada $DATE oleh $AUTHOR
  incidentBack: ← Kembali ke semua insiden
  pastIncidents: Insiden Masa Lalu
  pastIncidentsResolved: Diselesaikan dalam $MINUTES menit dengan $POSTS postingan
  liveStatus: Status Langsung
  overallUptime: Uptime keseluruhan $UPTIME%
  overallUptimeTitle: Uptime keseluruhan
  averageResponseTime: Waktu respons rata-rata $TIMEms
  averageResponseTimeTitle: Respon rata-rata
  sevelDayResponseTime: Waktu respons 7 hari
  responseTimeMs: Waktu respons (ms)
  up: Aktif
  down: Non-aktif
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: Halaman ini [open source]($REPO), dikembangkan oleh [Habib Rohman](https://github.com/hexatester) dengan menggunakan [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Batas tarif terlampaui
  rateLimitExceededIntro: Anda telah melebihi jumlah permintaan yang dapat Anda lakukan dalam satu jam, jadi Anda harus menunggu sebelum mengakses situs web ini lagi. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub untuk terus menggunakan situs web ini.
  rateLimitExceededWhatDoesErrorMean: Apa arti kesalahan ini?
  rateLimitExceededErrorMeaning: Situs web ini menggunakan API GitHub untuk mengakses data waktu nyata tentang status situs web kami. Secara default, GitHub mengizinkan setiap alamat IP 60 permintaan per jam, yang telah Anda gunakan.
  rateLimitExceededErrorHowCanFix: Bagaimana cara memperbaikinya?
  rateLimitExceededErrorFix: Anda dapat menunggu satu jam lagi dan batas alamat IP Anda akan dipulihkan. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub Anda, yang memberi Anda 5.000 permintaan tambahan per jam.
  rateLimitExceededGeneratePAT: Pelajari cara membuat Token Akses Pribadi
  rateLimitExceededHasSet: Anda memiliki set token akses pribadi.
  rateLimitExceededRemoveToken: Hapus token
  rateLimitExceededGitHubPAT: Token Akses Pribadi GitHub
  rateLimitExceededCopyPastePAT: Salin dan tempel token Anda
  rateLimitExceededSaveToken: Simpan token
  errorTitle: Terjadi kesalahan
  errorIntro: Terjadi kesalahan saat mencoba mendapatkan detail status terbaru.
  errorText: Anda dapat mencoba lagi dalam beberapa saat.
  errorHome: Buka beranda

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
